// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TavisApi.Context;

#nullable disable

namespace TavisApi.Migrations
{
    [DbContext(typeof(TavisContext))]
    [Migration("20220626151158_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tavis.Models.FeatureList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("BackwardsCompat")
                        .HasColumnType("bit");

                    b.Property<bool>("CloudGaming")
                        .HasColumnType("bit");

                    b.Property<bool>("Crossplay")
                        .HasColumnType("bit");

                    b.Property<bool>("EaPlay")
                        .HasColumnType("bit");

                    b.Property<int?>("FeatureListOfGameId")
                        .HasColumnType("int");

                    b.Property<bool>("GamePass")
                        .HasColumnType("bit");

                    b.Property<bool>("GamePreview")
                        .HasColumnType("bit");

                    b.Property<bool>("GamesWithGold")
                        .HasColumnType("bit");

                    b.Property<bool>("Hdr")
                        .HasColumnType("bit");

                    b.Property<bool>("IdAtXbox")
                        .HasColumnType("bit");

                    b.Property<bool>("NotBackwardsCompat")
                        .HasColumnType("bit");

                    b.Property<bool>("OnSteam")
                        .HasColumnType("bit");

                    b.Property<bool>("OneXEnhanced")
                        .HasColumnType("bit");

                    b.Property<bool>("OptimizedForSeries")
                        .HasColumnType("bit");

                    b.Property<bool>("PcGamePass")
                        .HasColumnType("bit");

                    b.Property<bool>("PlayAnywhere")
                        .HasColumnType("bit");

                    b.Property<bool>("SmartDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferableProgress")
                        .HasColumnType("bit");

                    b.Property<bool>("xCloudTouch")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FeatureListOfGameId")
                        .IsUnique()
                        .HasFilter("[FeatureListOfGameId] IS NOT NULL");

                    b.ToTable("FeatureLists");
                });

            modelBuilder.Entity("Tavis.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AchievementCount")
                        .HasColumnType("int");

                    b.Property<double?>("BaseCompletionEstimate")
                        .HasColumnType("float");

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FullCompletionEstimate")
                        .HasColumnType("float");

                    b.Property<int?>("GamersCompleted")
                        .HasColumnType("int");

                    b.Property<int?>("GamersWithGame")
                        .HasColumnType("int");

                    b.Property<int?>("Gamerscore")
                        .HasColumnType("int");

                    b.Property<double?>("InstallSize")
                        .HasColumnType("float");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ServerClosure")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SiteRating")
                        .HasColumnType("float");

                    b.Property<double?>("SiteRatio")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrueAchievement")
                        .HasColumnType("int");

                    b.Property<int>("TrueAchievementId")
                        .HasColumnType("int");

                    b.Property<bool>("Unobtainables")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Tavis.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("Tavis.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Third Person Shooter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Action Horror"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Action-Adventure"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Action-RPG"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Role Playing"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hack & Slash"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aerial"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Vehicular Combat"
                        },
                        new
                        {
                            Id = 12,
                            Name = "American Football"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Arcade Racing"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Automobile"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Australian Football"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Baseball"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 18,
                            Name = "First Person Shooter"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Battle Royale"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Beat 'em up"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bowling"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Boxing"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bull Sports"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Card & Board"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Casino"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Collectible Card Game"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Collection"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Point & Click"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cricket"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cue Sports"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Dance"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Darts"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Dodgeball"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Dungeon Crawler"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Educational & Trivia"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Party"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Equestrian Sports"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Fishing"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Handball"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Health & Fitness"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Hockey"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Hunting"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Management"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Mech"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Metroidvania"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Mixed Martial Arts"
                        },
                        new
                        {
                            Id = 54,
                            Name = "MMO"
                        },
                        new
                        {
                            Id = 55,
                            Name = "MOBA"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Motocross"
                        },
                        new
                        {
                            Id = 57,
                            Name = "On Rails"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Naval"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Paintball"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Pinball"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Real Time"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Roguelite"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Rugby"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Run & Gun"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Shoot 'em up"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Simulation Racing"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Skateboarding"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Skiing"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Snowboarding"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Survival Horror"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Tower Defence"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Visual Novel"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Volleyball"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Wrestling"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Turn Based"
                        });
                });

            modelBuilder.Entity("Tavis.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrueAchievementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Ohio",
                            IsActive = true,
                            Name = "kT Echo",
                            Region = "United States",
                            TrueAchievementId = 104571
                        },
                        new
                        {
                            Id = 2,
                            Area = "Ohio",
                            IsActive = true,
                            Name = "eohjay",
                            Region = "United States",
                            TrueAchievementId = 266752
                        },
                        new
                        {
                            Id = 3,
                            Area = "Ohio",
                            IsActive = true,
                            Name = "IronFistofSnuff",
                            Region = "United States",
                            TrueAchievementId = 405202
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "zzScanMan1",
                            TrueAchievementId = 461682
                        },
                        new
                        {
                            Id = 5,
                            Area = "Georgia",
                            IsActive = true,
                            Name = "SwiftSupafly",
                            Region = "United States",
                            TrueAchievementId = 691631
                        },
                        new
                        {
                            Id = 6,
                            Area = "New York",
                            IsActive = true,
                            Name = "DubstepEdgelord",
                            Region = "United States",
                            TrueAchievementId = 644155
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Infamous",
                            Region = "England",
                            TrueAchievementId = 518665
                        },
                        new
                        {
                            Id = 8,
                            Area = "California",
                            IsActive = true,
                            Name = "Luke17000",
                            Region = "United States",
                            TrueAchievementId = 1013881
                        },
                        new
                        {
                            Id = 9,
                            Area = "Kentucky",
                            IsActive = true,
                            Name = "lucas1987",
                            Region = "United States",
                            TrueAchievementId = 4838
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Fine Feat",
                            Region = "Austrailia",
                            TrueAchievementId = 695506
                        },
                        new
                        {
                            Id = 11,
                            Area = "Ontario",
                            IsActive = true,
                            Name = "smrnov",
                            Region = "Canada",
                            TrueAchievementId = 1815
                        },
                        new
                        {
                            Id = 12,
                            Area = "Georgia",
                            IsActive = true,
                            Name = "Sir Paulygon",
                            Region = "United States",
                            TrueAchievementId = 746750
                        },
                        new
                        {
                            Id = 13,
                            Area = "Victoria",
                            IsActive = true,
                            Name = "Rossco7530",
                            Region = "Austrailia",
                            TrueAchievementId = 385301
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "True Veteran",
                            Region = "Austrailia",
                            TrueAchievementId = 992494
                        },
                        new
                        {
                            Id = 15,
                            Area = "New Zealand",
                            IsActive = true,
                            Name = "CasualExile",
                            Region = "New Zealand",
                            TrueAchievementId = 561724
                        },
                        new
                        {
                            Id = 16,
                            Area = "Wisconsin",
                            IsActive = true,
                            Name = "darkwing1232",
                            Region = "United States",
                            TrueAchievementId = 644384
                        },
                        new
                        {
                            Id = 17,
                            Area = "Suffolk",
                            IsActive = true,
                            Name = "JimbotUK",
                            Region = "England",
                            TrueAchievementId = 567743
                        },
                        new
                        {
                            Id = 18,
                            Area = "Hesse",
                            IsActive = true,
                            Name = "xMagicMunKix",
                            Region = "Germany",
                            TrueAchievementId = 312377
                        },
                        new
                        {
                            Id = 19,
                            Area = "New York",
                            IsActive = true,
                            Name = "Inferno118",
                            Region = "United States",
                            TrueAchievementId = 405939
                        },
                        new
                        {
                            Id = 20,
                            Area = "Hesse",
                            IsActive = true,
                            Name = "AC Rock3tman",
                            Region = "Germany",
                            TrueAchievementId = 503921
                        },
                        new
                        {
                            Id = 21,
                            Area = "Michigan",
                            IsActive = true,
                            Name = "tackleglass54",
                            Region = "United States",
                            TrueAchievementId = 585579
                        },
                        new
                        {
                            Id = 22,
                            Area = "Illinois",
                            IsActive = true,
                            Name = "IcyThrasher",
                            Region = "United States",
                            TrueAchievementId = 115320
                        },
                        new
                        {
                            Id = 23,
                            Area = "Texas",
                            IsActive = true,
                            Name = "TXMOOK",
                            Region = "United States",
                            TrueAchievementId = 1872
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "BemusedBox",
                            Region = "England",
                            TrueAchievementId = 5540
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "nuttywray",
                            Region = "England",
                            TrueAchievementId = 292068
                        },
                        new
                        {
                            Id = 26,
                            Area = "Missouri",
                            IsActive = true,
                            Name = "Christoph 5782",
                            Region = "United States",
                            TrueAchievementId = 441743
                        },
                        new
                        {
                            Id = 27,
                            Area = "Quebec",
                            IsActive = true,
                            Name = "Mtld",
                            Region = "Canada",
                            TrueAchievementId = 8962
                        },
                        new
                        {
                            Id = 28,
                            Area = "Virginia",
                            IsActive = true,
                            Name = "Lw N1GHTM4R3",
                            Region = "United States",
                            TrueAchievementId = 978641
                        },
                        new
                        {
                            Id = 29,
                            Area = "Nottinghamshire",
                            IsActive = true,
                            Name = "Erutaerc",
                            Region = "England",
                            TrueAchievementId = 75572
                        },
                        new
                        {
                            Id = 30,
                            Area = "Hungary",
                            IsActive = true,
                            Name = "WildWhiteNoise",
                            Region = "Hungary",
                            TrueAchievementId = 332637
                        },
                        new
                        {
                            Id = 31,
                            Area = "Rhineland-Palatinate",
                            IsActive = true,
                            Name = "GD GodSpeed",
                            Region = "Germany",
                            TrueAchievementId = 767838
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            Name = "Legohead 1977",
                            Region = "England",
                            TrueAchievementId = 273370
                        },
                        new
                        {
                            Id = 33,
                            Area = "California",
                            IsActive = true,
                            Name = "Saurvivalist",
                            Region = "United States",
                            TrueAchievementId = 1001899
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            Name = "UltimateDespair",
                            Region = "England",
                            TrueAchievementId = 386783
                        },
                        new
                        {
                            Id = 35,
                            Area = "Michigan",
                            IsActive = true,
                            Name = "radnonnahs",
                            Region = "United States",
                            TrueAchievementId = 483713
                        },
                        new
                        {
                            Id = 36,
                            IsActive = true,
                            Name = "Wakapeil",
                            Region = "Sweden",
                            TrueAchievementId = 316981
                        },
                        new
                        {
                            Id = 37,
                            Area = "North Carolina",
                            IsActive = true,
                            Name = "DaDuelingDonuts",
                            Region = "United States",
                            TrueAchievementId = 661240
                        },
                        new
                        {
                            Id = 38,
                            Area = "New Jersey",
                            IsActive = true,
                            Name = "Oriole2682",
                            Region = "United States",
                            TrueAchievementId = 251492
                        },
                        new
                        {
                            Id = 39,
                            Area = "Washington",
                            IsActive = true,
                            Name = "NBA Kirkland",
                            Region = "United States",
                            TrueAchievementId = 18165
                        },
                        new
                        {
                            Id = 40,
                            Area = "North Carolina",
                            IsActive = true,
                            Name = "Xx Phatryda xX",
                            Region = "United States",
                            TrueAchievementId = 540888
                        },
                        new
                        {
                            Id = 41,
                            IsActive = true,
                            Name = "Fista Roboto",
                            Region = "Austrailia",
                            TrueAchievementId = 514795
                        },
                        new
                        {
                            Id = 42,
                            Area = "Florida",
                            IsActive = true,
                            Name = "HegemonicHater",
                            Region = "United States",
                            TrueAchievementId = 431830
                        },
                        new
                        {
                            Id = 43,
                            IsActive = true,
                            Name = "Team Brether",
                            Region = "England",
                            TrueAchievementId = 109626
                        },
                        new
                        {
                            Id = 44,
                            Area = "Oklahoma",
                            IsActive = true,
                            Name = "Mattism",
                            Region = "United States",
                            TrueAchievementId = 17362
                        },
                        new
                        {
                            Id = 45,
                            IsActive = true,
                            Name = "Alyssiya",
                            Region = "England",
                            TrueAchievementId = 667139
                        },
                        new
                        {
                            Id = 46,
                            Area = "Georgia",
                            IsActive = true,
                            Name = "MajinFro",
                            Region = "United States",
                            TrueAchievementId = 389388
                        },
                        new
                        {
                            Id = 47,
                            Area = "Florida",
                            IsActive = true,
                            Name = "Whisperin Clown",
                            Region = "United States",
                            TrueAchievementId = 460875
                        },
                        new
                        {
                            Id = 48,
                            Area = "New Hampshire",
                            IsActive = true,
                            Name = "Mental Knight 5",
                            Region = "United States",
                            TrueAchievementId = 273989
                        },
                        new
                        {
                            Id = 49,
                            IsActive = true,
                            Name = "ChinDocta",
                            Region = "Austrailia",
                            TrueAchievementId = 473608
                        },
                        new
                        {
                            Id = 50,
                            Area = "Devon",
                            IsActive = true,
                            Name = "A1exRD",
                            Region = "England",
                            TrueAchievementId = 108134
                        },
                        new
                        {
                            Id = 51,
                            Area = "Washington",
                            IsActive = true,
                            Name = "Ethigy",
                            Region = "United States",
                            TrueAchievementId = 662432
                        },
                        new
                        {
                            Id = 52,
                            Area = "Rhineland-Palatinate",
                            IsActive = true,
                            Name = "Nichtl",
                            Region = "Germany",
                            TrueAchievementId = 596837
                        },
                        new
                        {
                            Id = 53,
                            Area = "Pennsylvania",
                            IsActive = true,
                            Name = "PangoBara",
                            Region = "United States",
                            TrueAchievementId = 507793
                        },
                        new
                        {
                            Id = 54,
                            Area = "Iowa",
                            IsActive = true,
                            Name = "HawkeyeBarry20",
                            Region = "United States",
                            TrueAchievementId = 548044
                        },
                        new
                        {
                            Id = 55,
                            Area = "New York",
                            IsActive = true,
                            Name = "KawiNinjaRider7",
                            Region = "United States",
                            TrueAchievementId = 636969
                        },
                        new
                        {
                            Id = 56,
                            IsActive = true,
                            Name = "BenL72",
                            Region = "England",
                            TrueAchievementId = 280034
                        },
                        new
                        {
                            Id = 57,
                            Area = "Minnesota",
                            IsActive = true,
                            Name = "Freamwhole",
                            Region = "United States",
                            TrueAchievementId = 276088
                        },
                        new
                        {
                            Id = 58,
                            Area = "Virginia",
                            IsActive = true,
                            Name = "Proulx",
                            Region = "United States",
                            TrueAchievementId = 78779
                        },
                        new
                        {
                            Id = 59,
                            IsActive = true,
                            Name = "zzUrbanSpaceman",
                            Region = "Austrailia",
                            TrueAchievementId = 60207
                        },
                        new
                        {
                            Id = 60,
                            IsActive = true,
                            Name = "A 0 E Monkey",
                            Region = "England",
                            TrueAchievementId = 27797
                        },
                        new
                        {
                            Id = 61,
                            Area = "Georgia",
                            IsActive = true,
                            Name = "Majinbro",
                            Region = "United States",
                            TrueAchievementId = 38595
                        },
                        new
                        {
                            Id = 62,
                            Area = "Connecticut",
                            IsActive = true,
                            Name = "Icefiretn",
                            Region = "United States",
                            TrueAchievementId = 126013
                        },
                        new
                        {
                            Id = 63,
                            Area = "Massachusetts",
                            IsActive = true,
                            Name = "LORDOFDOOKIE69",
                            Region = "United States",
                            TrueAchievementId = 130600
                        },
                        new
                        {
                            Id = 64,
                            Area = "North Carolina",
                            IsActive = true,
                            Name = "RetroChief1969",
                            Region = "United States",
                            TrueAchievementId = 685511
                        },
                        new
                        {
                            Id = 65,
                            Area = "California",
                            IsActive = true,
                            Name = "EldritchSS",
                            Region = "United States",
                            TrueAchievementId = 11497
                        },
                        new
                        {
                            Id = 66,
                            Area = "Tennessee",
                            IsActive = true,
                            Name = "rawkerdude",
                            Region = "United States",
                            TrueAchievementId = 25889
                        },
                        new
                        {
                            Id = 67,
                            Area = "Illinois",
                            IsActive = true,
                            Name = "iMaginaryy",
                            Region = "United States",
                            TrueAchievementId = 351310
                        },
                        new
                        {
                            Id = 68,
                            Area = "South Carolina",
                            IsActive = true,
                            Name = "Kez001",
                            Region = "United States",
                            TrueAchievementId = 15074
                        },
                        new
                        {
                            Id = 69,
                            IsActive = true,
                            Name = "WoodsMonk",
                            Region = "England",
                            TrueAchievementId = 46893
                        },
                        new
                        {
                            Id = 70,
                            Area = "Washington",
                            IsActive = true,
                            Name = "W1cked Girl",
                            Region = "United States",
                            TrueAchievementId = 391205
                        },
                        new
                        {
                            Id = 71,
                            Area = "Cardiff",
                            IsActive = true,
                            Name = "Kitty Skies",
                            Region = "Wales",
                            TrueAchievementId = 321249
                        },
                        new
                        {
                            Id = 72,
                            Area = "Connecticut",
                            IsActive = true,
                            Name = "MrGompers",
                            Region = "United States",
                            TrueAchievementId = 53128
                        },
                        new
                        {
                            Id = 73,
                            Area = "Netherlands",
                            IsActive = true,
                            Name = "GTKrouwel83",
                            Region = "Netherlands",
                            TrueAchievementId = 991656
                        },
                        new
                        {
                            Id = 74,
                            Area = "Kentucky",
                            IsActive = true,
                            Name = "CouchBurglar",
                            Region = "United States",
                            TrueAchievementId = 710980
                        },
                        new
                        {
                            Id = 75,
                            Area = "Virginia",
                            IsActive = true,
                            Name = "SprinkyDink",
                            Region = "United States",
                            TrueAchievementId = 391799
                        },
                        new
                        {
                            Id = 76,
                            IsActive = true,
                            Name = "boldyno1",
                            Region = "England",
                            TrueAchievementId = 57548
                        },
                        new
                        {
                            Id = 77,
                            Area = "Virginia",
                            IsActive = true,
                            Name = "FreakyRO",
                            Region = "United States",
                            TrueAchievementId = 389092
                        },
                        new
                        {
                            Id = 78,
                            Area = "Kansas",
                            IsActive = true,
                            Name = "hotcurls3088",
                            Region = "United States",
                            TrueAchievementId = 259643
                        },
                        new
                        {
                            Id = 79,
                            Area = "Georgia",
                            IsActive = true,
                            Name = "Kaiteh",
                            Region = "United States",
                            TrueAchievementId = 714727
                        },
                        new
                        {
                            Id = 80,
                            IsActive = true,
                            Name = "Yinga Garten",
                            Region = "United Kingdom",
                            TrueAchievementId = 107004
                        },
                        new
                        {
                            Id = 81,
                            Area = "Minnesota",
                            IsActive = true,
                            Name = "Skeptical Mario",
                            Region = "United States",
                            TrueAchievementId = 47628
                        },
                        new
                        {
                            Id = 82,
                            Area = "New Jersey",
                            IsActive = true,
                            Name = "WildwoodMike",
                            Region = "United States",
                            TrueAchievementId = 286696
                        },
                        new
                        {
                            Id = 83,
                            Area = "New Hampshire",
                            IsActive = true,
                            Name = "ChewieOnIce",
                            Region = "England",
                            TrueAchievementId = 115479
                        },
                        new
                        {
                            Id = 84,
                            Area = "Croatia",
                            IsActive = true,
                            Name = "Igneus DarkSide",
                            Region = "Croatia",
                            TrueAchievementId = 275395
                        },
                        new
                        {
                            Id = 85,
                            Area = "Ireland",
                            IsActive = true,
                            Name = "DavidMcC1989",
                            Region = "Ireland",
                            TrueAchievementId = 89301
                        },
                        new
                        {
                            Id = 86,
                            Area = "Pennsylvania",
                            IsActive = true,
                            Name = "RadicalSniper99",
                            Region = "United States",
                            TrueAchievementId = 378519
                        },
                        new
                        {
                            Id = 87,
                            Area = "Nevada",
                            IsActive = true,
                            Name = "Hotdogmcgee",
                            Region = "United States",
                            TrueAchievementId = 4860
                        },
                        new
                        {
                            Id = 88,
                            IsActive = true,
                            Name = "HenkeXD",
                            Region = "Sweden",
                            TrueAchievementId = 332575
                        },
                        new
                        {
                            Id = 89,
                            Area = "Maryland",
                            IsActive = true,
                            Name = "KooshMoose",
                            Region = "United States",
                            TrueAchievementId = 435315
                        },
                        new
                        {
                            Id = 90,
                            Area = "Virginia",
                            IsActive = true,
                            Name = "Xynvincible",
                            Region = "United States",
                            TrueAchievementId = 58478
                        },
                        new
                        {
                            Id = 91,
                            Area = "Wisconsin",
                            IsActive = true,
                            Name = "Whtthfgg",
                            Region = "United States",
                            TrueAchievementId = 365315
                        },
                        new
                        {
                            Id = 92,
                            Area = "Colorado",
                            IsActive = true,
                            Name = "PlayUltimate711",
                            Region = "United States",
                            TrueAchievementId = 125044
                        },
                        new
                        {
                            Id = 93,
                            Area = "British Columbia",
                            IsActive = true,
                            Name = "Seamus McLimey",
                            Region = "Canada",
                            TrueAchievementId = 119394
                        },
                        new
                        {
                            Id = 94,
                            Area = "Lancashire",
                            IsActive = true,
                            Name = "Northern Lass",
                            Region = "England",
                            TrueAchievementId = 40704
                        },
                        new
                        {
                            Id = 95,
                            Area = "California",
                            IsActive = true,
                            Name = "xNeo21x",
                            Region = "United States",
                            TrueAchievementId = 37540
                        },
                        new
                        {
                            Id = 96,
                            IsActive = true,
                            Name = "Redanian",
                            Region = "England",
                            TrueAchievementId = 401906
                        },
                        new
                        {
                            Id = 97,
                            Area = "New Jersey",
                            IsActive = true,
                            Name = "TBonePhone",
                            Region = "United States",
                            TrueAchievementId = 64912
                        },
                        new
                        {
                            Id = 98,
                            Area = "Lower Saxony",
                            IsActive = true,
                            Name = "IxGermanBeastxI",
                            Region = "Germany",
                            TrueAchievementId = 734459
                        },
                        new
                        {
                            Id = 99,
                            Area = "Georgia",
                            IsActive = true,
                            Name = "PhillipWendell",
                            Region = "United States",
                            TrueAchievementId = 78294
                        },
                        new
                        {
                            Id = 100,
                            IsActive = true,
                            Name = "C64 Mat",
                            Region = "England",
                            TrueAchievementId = 338344
                        },
                        new
                        {
                            Id = 101,
                            IsActive = true,
                            Name = "Benjii Redux",
                            Region = "Austrailia",
                            TrueAchievementId = 519817
                        },
                        new
                        {
                            Id = 102,
                            IsActive = true,
                            Name = "KATAKL1ZM",
                            Region = "England",
                            TrueAchievementId = 286468
                        },
                        new
                        {
                            Id = 103,
                            IsActive = true,
                            Name = "Mark B",
                            Region = "England",
                            TrueAchievementId = 408078
                        },
                        new
                        {
                            Id = 104,
                            Area = "Iowa",
                            IsActive = true,
                            Name = "Slayer Reigning",
                            Region = "United States",
                            TrueAchievementId = 82490
                        },
                        new
                        {
                            Id = 105,
                            Area = "Derbyshire",
                            IsActive = true,
                            Name = "xLAx JesteR",
                            Region = "England",
                            TrueAchievementId = 135630
                        },
                        new
                        {
                            Id = 106,
                            Area = "Ontario",
                            IsActive = true,
                            Name = "CrunchyGoblin68",
                            Region = "Canada",
                            TrueAchievementId = 450068
                        },
                        new
                        {
                            Id = 107,
                            Area = "Massachusetts",
                            IsActive = true,
                            Name = "SaucySlingo",
                            Region = "United States",
                            TrueAchievementId = 333080
                        },
                        new
                        {
                            Id = 108,
                            Area = "Lower Saxony",
                            IsActive = true,
                            Name = "III Torpedo III",
                            Region = "Germany",
                            TrueAchievementId = 94956
                        },
                        new
                        {
                            Id = 109,
                            IsActive = true,
                            Name = "Eliphelet77",
                            Region = "England",
                            TrueAchievementId = 78762
                        },
                        new
                        {
                            Id = 110,
                            Area = "Cardiff",
                            IsActive = true,
                            Name = "Lord Zell",
                            Region = "Wales",
                            TrueAchievementId = 434741
                        },
                        new
                        {
                            Id = 111,
                            Area = "Oregon",
                            IsActive = true,
                            Name = "Boda Yett",
                            Region = "United States",
                            TrueAchievementId = 907614
                        },
                        new
                        {
                            Id = 112,
                            Area = "Tennessee",
                            IsActive = true,
                            Name = "Not A Designer",
                            Region = "United States",
                            TrueAchievementId = 800715
                        },
                        new
                        {
                            Id = 113,
                            IsActive = true,
                            Name = "Muetschens",
                            Region = "Switzerland",
                            TrueAchievementId = 64293
                        },
                        new
                        {
                            Id = 114,
                            Area = "New York",
                            IsActive = true,
                            Name = "Big Ell",
                            Region = "United States",
                            TrueAchievementId = 64295
                        },
                        new
                        {
                            Id = 115,
                            Area = "New York",
                            IsActive = true,
                            Name = "K4rn4ge",
                            Region = "United States",
                            TrueAchievementId = 2898
                        },
                        new
                        {
                            Id = 116,
                            Area = "Texas",
                            IsActive = true,
                            Name = "bryan dot exe",
                            Region = "United States",
                            TrueAchievementId = 134205
                        },
                        new
                        {
                            Id = 117,
                            Area = "Slovenia",
                            IsActive = true,
                            Name = "Kaneman",
                            Region = "Slovenia",
                            TrueAchievementId = 410425
                        },
                        new
                        {
                            Id = 118,
                            Area = "Georgia",
                            IsActive = true,
                            Name = "DudeWithTheFace",
                            Region = "United States",
                            TrueAchievementId = 24047
                        },
                        new
                        {
                            Id = 119,
                            Area = "Indiana",
                            IsActive = true,
                            Name = "MadLefty2097",
                            Region = "United States",
                            TrueAchievementId = 684657
                        },
                        new
                        {
                            Id = 120,
                            Area = "California",
                            IsActive = true,
                            Name = "retstak",
                            Region = "United States",
                            TrueAchievementId = 447768
                        },
                        new
                        {
                            Id = 121,
                            Area = "Ohio",
                            IsActive = true,
                            Name = "Death Dealers",
                            Region = "United States",
                            TrueAchievementId = 615774
                        },
                        new
                        {
                            Id = 122,
                            Area = "New York",
                            IsActive = true,
                            Name = "Matrarch",
                            Region = "United States",
                            TrueAchievementId = 5581
                        },
                        new
                        {
                            Id = 123,
                            Area = "Pennsylvania",
                            IsActive = true,
                            Name = "omgeezus",
                            Region = "United States",
                            TrueAchievementId = 13608
                        },
                        new
                        {
                            Id = 124,
                            IsActive = true,
                            Name = "FlutteryChicken",
                            Region = "England",
                            TrueAchievementId = 7499
                        },
                        new
                        {
                            Id = 125,
                            Area = "Florida",
                            IsActive = true,
                            Name = "CarpeAdam79",
                            Region = "United States",
                            TrueAchievementId = 651526
                        },
                        new
                        {
                            Id = 126,
                            IsActive = true,
                            Name = "Hatton90",
                            Region = "England",
                            TrueAchievementId = 647169
                        },
                        new
                        {
                            Id = 127,
                            Area = "Indiana",
                            IsActive = true,
                            Name = "Triple Triad777",
                            Region = "United States",
                            TrueAchievementId = 538641
                        },
                        new
                        {
                            Id = 128,
                            Area = "Texas",
                            IsActive = true,
                            Name = "Buffs",
                            Region = "United States",
                            TrueAchievementId = 105056
                        },
                        new
                        {
                            Id = 129,
                            Area = "Pennsylvania",
                            IsActive = true,
                            Name = "BPBPBPBPBPBPBP",
                            Region = "United States",
                            TrueAchievementId = 38717
                        },
                        new
                        {
                            Id = 130,
                            Area = "West Virginia",
                            IsActive = true,
                            Name = "CHERRY CHEERIOS",
                            Region = "United States",
                            TrueAchievementId = 266948
                        },
                        new
                        {
                            Id = 131,
                            Area = "Jamaica",
                            IsActive = true,
                            Name = "DJB Hustlin",
                            Region = "Jamaica",
                            TrueAchievementId = 54140
                        },
                        new
                        {
                            Id = 132,
                            Area = "Ontario",
                            IsActive = true,
                            Name = "ITS ALivEx",
                            Region = "Canada",
                            TrueAchievementId = 328184
                        },
                        new
                        {
                            Id = 133,
                            Area = "New York",
                            IsActive = true,
                            Name = "TheAlphaSeagull",
                            Region = "United States",
                            TrueAchievementId = 893882
                        },
                        new
                        {
                            Id = 134,
                            Area = "Ontario",
                            IsActive = true,
                            Name = "mdp 73",
                            Region = "Canada",
                            TrueAchievementId = 1995
                        },
                        new
                        {
                            Id = 135,
                            IsActive = true,
                            Name = "ListlessDragon",
                            Region = "Switzerland",
                            TrueAchievementId = 533284
                        },
                        new
                        {
                            Id = 136,
                            Area = "Wisconsin",
                            IsActive = true,
                            Name = "WeezyFuzz",
                            Region = "United States",
                            TrueAchievementId = 435101
                        },
                        new
                        {
                            Id = 137,
                            Area = "Louisiana",
                            IsActive = true,
                            Name = "ILethalStang",
                            Region = "United States",
                            TrueAchievementId = 628247
                        },
                        new
                        {
                            Id = 138,
                            Area = "Ontario",
                            IsActive = true,
                            Name = "IrishWarrior022",
                            Region = "Canada",
                            TrueAchievementId = 392553
                        },
                        new
                        {
                            Id = 139,
                            Area = "Arizona",
                            IsActive = true,
                            Name = "General Tynstar",
                            Region = "United States",
                            TrueAchievementId = 6420
                        },
                        new
                        {
                            Id = 140,
                            Area = "British Columbia",
                            IsActive = true,
                            Name = "Ace",
                            Region = "Canada",
                            TrueAchievementId = 684086
                        },
                        new
                        {
                            Id = 141,
                            Area = "Ohio",
                            IsActive = true,
                            Name = "DirtyMcNasty126",
                            Region = "United States",
                            TrueAchievementId = 1022271
                        },
                        new
                        {
                            Id = 142,
                            Area = "Michigan",
                            IsActive = true,
                            Name = "Bsmittel",
                            Region = "United States",
                            TrueAchievementId = 439921
                        },
                        new
                        {
                            Id = 143,
                            Area = "Texas",
                            IsActive = true,
                            Name = "SKOOT2006",
                            Region = "United States",
                            TrueAchievementId = 387165
                        },
                        new
                        {
                            Id = 144,
                            IsActive = true,
                            Name = "Simpso",
                            Region = "England",
                            TrueAchievementId = 111184
                        },
                        new
                        {
                            Id = 145,
                            Area = "Illinois",
                            IsActive = true,
                            Name = "BlazeFlareon",
                            Region = "United States",
                            TrueAchievementId = 451792
                        },
                        new
                        {
                            Id = 146,
                            IsActive = true,
                            Name = "MrWolfw00d",
                            Region = "England",
                            TrueAchievementId = 375330
                        },
                        new
                        {
                            Id = 147,
                            IsActive = true,
                            Name = "AgileDuke",
                            Region = "England",
                            TrueAchievementId = 50502
                        },
                        new
                        {
                            Id = 148,
                            Area = "Wisconsin",
                            IsActive = true,
                            Name = "JeffMomm",
                            Region = "United States",
                            TrueAchievementId = 349158
                        },
                        new
                        {
                            Id = 149,
                            IsActive = true,
                            Name = "MattiasAnderson",
                            Region = "Sweden",
                            TrueAchievementId = 349605
                        },
                        new
                        {
                            Id = 150,
                            Area = "Colorado",
                            IsActive = true,
                            Name = "Kyleia",
                            Region = "United States",
                            TrueAchievementId = 711432
                        },
                        new
                        {
                            Id = 151,
                            IsActive = true,
                            Name = "Miller N7",
                            Region = "England",
                            TrueAchievementId = 896662
                        },
                        new
                        {
                            Id = 152,
                            Area = "North Carolina",
                            IsActive = true,
                            Name = "Fresh336669",
                            Region = "United States",
                            TrueAchievementId = 380552
                        },
                        new
                        {
                            Id = 153,
                            Area = "Suffolk",
                            IsActive = true,
                            Name = "MOT Astro",
                            Region = "England",
                            TrueAchievementId = 721181
                        },
                        new
                        {
                            Id = 154,
                            Area = "California",
                            IsActive = true,
                            Name = "Facial La Fleur",
                            Region = "United States",
                            TrueAchievementId = 4936
                        },
                        new
                        {
                            Id = 155,
                            Area = "Ohio",
                            IsActive = true,
                            Name = "AnonymousODB",
                            Region = "United States",
                            TrueAchievementId = 437038
                        },
                        new
                        {
                            Id = 156,
                            Area = "Maryland",
                            IsActive = true,
                            Name = "FuFuCuddilyPoof",
                            Region = "United States",
                            TrueAchievementId = 635863
                        });
                });

            modelBuilder.Entity("Tavis.Models.PlayerGame", b =>
                {
                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("AchievementCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Gamerscore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUnlock")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotForContests")
                        .HasColumnType("bit");

                    b.Property<int?>("Ownership")
                        .HasColumnType("int");

                    b.Property<int?>("Platform")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrueAchievement")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGames");
                });

            modelBuilder.Entity("Tavis.Models.FeatureList", b =>
                {
                    b.HasOne("Tavis.Models.Game", "Game")
                        .WithOne("FeatureList")
                        .HasForeignKey("Tavis.Models.FeatureList", "FeatureListOfGameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Tavis.Models.GameGenre", b =>
                {
                    b.HasOne("Tavis.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tavis.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Tavis.Models.PlayerGame", b =>
                {
                    b.HasOne("Tavis.Models.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tavis.Models.Player", "Player")
                        .WithMany("PlayerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Tavis.Models.Game", b =>
                {
                    b.Navigation("FeatureList");

                    b.Navigation("GameGenres");

                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("Tavis.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("Tavis.Models.Player", b =>
                {
                    b.Navigation("PlayerGames");
                });
#pragma warning restore 612, 618
        }
    }
}
