name: Connect to Server and Create Folder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known_hosts
      run: ssh-keyscan -H ${{ secrets.VPS_SERVER_IP }} >> ~/.ssh/known_hosts
      env:
        HOST: ${{ secrets.VPS_SERVER_IP }}
    - name: Connect to server 1
      run: |
          ssh -i ~/.ssh/id_rsa root@${{secrets.VPS_SERVER_IP}} << EOF
          mkdir folder
          EOF
    - name: Connect to server 
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_SERVER_IP }} << EOF
        mkdir workflow_testing
        EOF
