name: Deploy code to VPS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and pull code
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh root@170.249.237.92 "cd tavis && git pull"

