name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    defaults:
        run:
          working-directory: ./TavisApi/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSHPASS
        run: ls