name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create folder on VPS
        run: |
          sshpass -p ${{secrets.SSH_PASSWORD}} ssh root@170.249.237.92 "mkdir -p /path/to/your/folder"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
